# PyRamen

In [ ]:
# import pandas first!
import pandas as pd

In [9]:
#load csvs
listingsdf = pd.read_csv('menu_data.csv')
listingsdf.shape

(32, 5)

In [10]:
listingsdf.head()

,item,category,description,price,cost
0,edamame,appetizers,"boiled soybeans, maldon sea salt",4.0,1
1,house salad,appetizers,"mixed greens, cherry tomatoes, cucumber, house...",4.0,2
2,cucumber sunomono salad,appetizers,"cucumber, ponzu dressing, pickled ginger sprou...",5.0,2
3,hiyashi wakame seaweed salad,appetizers,"sweet soy-marinated wakame seaweed threads, pi...",5.0,2
4,agedashi tofu,appetizers,"tempura battered tofu, katsuobushi, tsuyu brot...",5.0,2

In [11]:
#load sales data
sales = pd.read_csv('sales_data.csv')

sales.head()

   Line_Item_ID      Date  Credit_Card_Number  Quantity             Menu_Item
0             1  1/1/2017        7.437930e+15         1      spicy miso ramen
1             2  1/1/2017        7.437930e+15         1      spicy miso ramen
2             3  1/1/2017        8.421920e+15         3     tori paitan ramen
3             4  1/1/2017        8.421920e+15         3     tori paitan ramen
4             5  1/1/2017        4.787310e+15         1  truffle butter ramen

In [12]:
#how many rows
len(sales)

74124

In [13]:
#rename columns for merging
listingsdf = listingsdf.rename({'Quantity':'Menu_Item'}, axis='columns')
listingsdf

,item,category,description,price,cost
0,edamame,appetizers,"boiled soybeans, maldon sea salt",4.0,1
1,house salad,appetizers,"mixed greens, cherry tomatoes, cucumber, house...",4.0,2
2,cucumber sunomono salad,appetizers,"cucumber, ponzu dressing, pickled ginger sprou...",5.0,2
3,hiyashi wakame seaweed salad,appetizers,"sweet soy-marinated wakame seaweed threads, pi...",5.0,2
4,agedashi tofu,appetizers,"tempura battered tofu, katsuobushi, tsuyu brot...",5.0,2
5,hiyayakko tofu,appetizers,"chilled soft tofu, house shoyu, katsuobushi, g...",5.0,2
6,pork floss bao,appetizers,"two steamed buns, minced lean slow braised nim...",4.0,2
7,kakuni bao,appetizers,"two steamed buns, chopped fatty slow braised n...",6.0,3
8,edamame fried gyoza (vegan),appetizers,six crispy fried edamame and cabbage pot stick...,6.0,3
9,fried gyoza,appetizers,six cripsy fried pork and vegetable pot sticke...,6.0,6
10,takoyaki,appetizers,"six octopus-filled fried fritters, kewpie mayo...",6.0,3
11,rock shrimp tempura,appetizers,"deep fried tempura battered rock shrimp, srira...",6.0,3
12,soft-shell crab tempura,appetizers,"single deep fried soft-shell crab, tsuyu dippi...",6.0,3
13,ebi katsu shrimp bao,appetizers,"two steamed buns, panko-crusted fried shrimp p...",6.0,3
14,nagomi shoyu,entree,shoyu seasoned clear double stock (organic chi...,11.0,5
15,shio ramen,entree,sea salt seasoned clear double stock (organic ...,11.0,5
16,spicy miso ramen,entree,house togarashi miso blend + niman ranch pork ...,12.0,5
17,vegetarian spicy miso,entree,house togarashi miso blend + vegan dashi; temp...,12.0,5
18,miso crab ramen,entree,house miso crab blend + vegan dashi; slow brai...,12.0,6
19,soft-shell miso crab ramen,entree,house miso crab blend + vegan dashi; fried who...,14.0,7
20,tori paitan ramen,entree,"rich, shoyu seasoned double stock (organic chi...",13.0,6
21,tonkotsu ramen,entree,"rich, shoyi seasoned niman ranch pork bone sto...",13.0,6
22,burnt garlic tonkotsu ramen,entree,"rich, shoyi and burnt garlic seasoned niman ra...",14.0,6
23,vegetarian curry + king trumpet mushroom ramen,entree,house curry blend + vegan dashi; fried king tr...,13.0,7
24,truffle butter ramen,entree,"rich, shoyu seasoned niman ranch prok bone sto...",14.0,7
25,green tea,drinks,green tea,2.5,1
26,coke,drinks,Coca Cola soda,2.0,1
27,black sesame ice cream,desserts,"house-made black sesame ice cream, valrhona ch...",5.0,2
28,matcha ice cream,desserts,"house-made matcha ice cream, white chocolate p...",5.0,2
29,mango mochi ice cream,desserts,two rice-cake bonbons filled with strawberry i...,5.0,2
30,strawberry mochi ice cream,desserts,two rice-cake bonbons filled with strawberry i...,5.0,2
31,black sesame creme brulee,desserts,house made black sesame infused creme brulee; ...,6.0,3

In [25]:
#Combining dataframes
dfjoin = pd.merge(sales,listingsdf, on='Menu_Item', how='inner')
dfjoin

KeyError: 'Menu_Item'

In [15]:
#removing unneeded columns
dfjoin = dfjoin.drop(columns=['',''])
dfjoin.head()

NameError: name 'dfjoin' is not defined

In [16]:
# create pivot table by product groups
import numpy as np

dfpivot = pd.pivot_table(dfjoin, values=['Quantity', 'Price','COGS'],
                        index=['Product'],aggfunc=np.sum)
dfpivot

NameError: name 'dfjoin' is not defined

In [17]:
#calculating profit and making another column for it
dfpivot['Profit'] = (dfpivot['Price'] - dfpivot['COGS'])
dfpivot

NameError: name 'dfpivot' is not defined

In [18]:
#export to csv
dfpivot.to_csv('ProductReport.csv')

NameError: name 'dfpivot' is not defined